<?php

namespace Sprint\Migration;

class Test_iblock_migration20230214144913 extends Version
{
    protected $description = 'Migration for iblock with code "Test"';

    protected $moduleVersion = '4.2.4';

    /**
     * @throws Exceptions\HelperException
     * @return bool|void
     */
    public function up()
    {
        $helper = $this->getHelperManager();
        $helper->Iblock()->saveIblockType([
            'ID' => 'test',
            'SECTIONS' => 'Y',
            'EDIT_FILE_BEFORE' => '',
            'EDIT_FILE_AFTER' => '',
            'IN_RSS' => 'N',
            'SORT' => '500',
            'LANG' => [
                'ru' => [
                    'NAME' => 'Test',
                    'SECTION_NAME' => '',
                    'ELEMENT_NAME' => '',
                ],
                'en' => [
                    'NAME' => 'Test',
                    'SECTION_NAME' => '',
                    'ELEMENT_NAME' => '',
                ],
            ],
        ]);
        $iblockId = $helper->Iblock()->saveIblock([
            'IBLOCK_TYPE_ID' => 'test',
            'LID' => [
                0 => 's1',
            ],
            'CODE' => 'Test',
            'API_CODE' => 'Test',
            'REST_ON' => 'N',
            'NAME' => 'Test',
            'ACTIVE' => 'Y',
            'SORT' => '500',
            'LIST_PAGE_URL' => '#SITE_DIR#/test/index.php?ID=#IBLOCK_ID#',
            'DETAIL_PAGE_URL' => '#SITE_DIR#/test/detail.php?ID=#ELEMENT_ID#',
            'SECTION_PAGE_URL' => '#SITE_DIR#/test/list.php?SECTION_ID=#SECTION_ID#',
            'CANONICAL_PAGE_URL' => '',
            'PICTURE' => null,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'RSS_TTL' => '24',
            'RSS_ACTIVE' => 'Y',
            'RSS_FILE_ACTIVE' => 'N',
            'RSS_FILE_LIMIT' => null,
            'RSS_FILE_DAYS' => null,
            'RSS_YANDEX_ACTIVE' => 'N',
            'XML_ID' => null,
            'INDEX_ELEMENT' => 'Y',
            'INDEX_SECTION' => 'Y',
            'WORKFLOW' => 'N',
            'BIZPROC' => 'N',
            'SECTION_CHOOSER' => 'L',
            'LIST_MODE' => '',
            'RIGHTS_MODE' => 'S',
            'SECTION_PROPERTY' => 'N',
            'PROPERTY_INDEX' => 'N',
            'VERSION' => '1',
            'LAST_CONV_ELEMENT' => '0',
            'SOCNET_GROUP_ID' => null,
            'EDIT_FILE_BEFORE' => '',
            'EDIT_FILE_AFTER' => '',
            'SECTIONS_NAME' => 'Разделы',
            'SECTION_NAME' => 'Раздел',
            'ELEMENTS_NAME' => 'Элементы',
            'ELEMENT_NAME' => 'Элемент',
            'EXTERNAL_ID' => null,
            'LANG_DIR' => '/var/www/html/bitrix-starter-pack',
            'SERVER_NAME' => '',
            'IPROPERTY_TEMPLATES' => [
            ],
            'ELEMENT_ADD' => 'Добавить элемент',
            'ELEMENT_EDIT' => 'Изменить элемент',
            'ELEMENT_DELETE' => 'Удалить элемент',
            'SECTION_ADD' => 'Добавить раздел',
            'SECTION_EDIT' => 'Изменить раздел',
            'SECTION_DELETE' => 'Удалить раздел',
        ]);
        $helper->Iblock()->saveIblockFields($iblockId, [
            'IBLOCK_SECTION' => [
                'NAME' => 'Привязка к разделам',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => [
                    'KEEP_IBLOCK_SECTION_ID' => 'N',
                ],
            ],
            'ACTIVE' => [
                'NAME' => 'Активность',
                'IS_REQUIRED' => 'Y',
                'DEFAULT_VALUE' => 'Y',
            ],
            'ACTIVE_FROM' => [
                'NAME' => 'Начало активности',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => '',
            ],
            'ACTIVE_TO' => [
                'NAME' => 'Окончание активности',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => '',
            ],
            'SORT' => [
                'NAME' => 'Сортировка',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => '0',
            ],
            'NAME' => [
                'NAME' => 'Название',
                'IS_REQUIRED' => 'Y',
                'DEFAULT_VALUE' => '',
            ],
            'PREVIEW_PICTURE' => [
                'NAME' => 'Картинка для анонса',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => [
                    'FROM_DETAIL' => 'N',
                    'SCALE' => 'N',
                    'WIDTH' => '',
                    'HEIGHT' => '',
                    'IGNORE_ERRORS' => 'N',
                    'METHOD' => 'resample',
                    'COMPRESSION' => 95,
                    'DELETE_WITH_DETAIL' => 'N',
                    'UPDATE_WITH_DETAIL' => 'N',
                    'USE_WATERMARK_TEXT' => 'N',
                    'WATERMARK_TEXT' => '',
                    'WATERMARK_TEXT_FONT' => '',
                    'WATERMARK_TEXT_COLOR' => '',
                    'WATERMARK_TEXT_SIZE' => '',
                    'WATERMARK_TEXT_POSITION' => 'tl',
                    'USE_WATERMARK_FILE' => 'N',
                    'WATERMARK_FILE' => '',
                    'WATERMARK_FILE_ALPHA' => '',
                    'WATERMARK_FILE_POSITION' => 'tl',
                    'WATERMARK_FILE_ORDER' => null,
                ],
            ],
            'PREVIEW_TEXT_TYPE' => [
                'NAME' => 'Тип описания для анонса',
                'IS_REQUIRED' => 'Y',
                'DEFAULT_VALUE' => 'text',
            ],
            'PREVIEW_TEXT' => [
                'NAME' => 'Описание для анонса',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => '',
            ],
            'DETAIL_PICTURE' => [
                'NAME' => 'Детальная картинка',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => [
                    'SCALE' => 'N',
                    'WIDTH' => '',
                    'HEIGHT' => '',
                    'IGNORE_ERRORS' => 'N',
                    'METHOD' => 'resample',
                    'COMPRESSION' => 95,
                    'USE_WATERMARK_TEXT' => 'N',
                    'WATERMARK_TEXT' => '',
                    'WATERMARK_TEXT_FONT' => '',
                    'WATERMARK_TEXT_COLOR' => '',
                    'WATERMARK_TEXT_SIZE' => '',
                    'WATERMARK_TEXT_POSITION' => 'tl',
                    'USE_WATERMARK_FILE' => 'N',
                    'WATERMARK_FILE' => '',
                    'WATERMARK_FILE_ALPHA' => '',
                    'WATERMARK_FILE_POSITION' => 'tl',
                    'WATERMARK_FILE_ORDER' => null,
                ],
            ],
            'DETAIL_TEXT_TYPE' => [
                'NAME' => 'Тип детального описания',
                'IS_REQUIRED' => 'Y',
                'DEFAULT_VALUE' => 'text',
            ],
            'DETAIL_TEXT' => [
                'NAME' => 'Детальное описание',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => '',
            ],
            'XML_ID' => [
                'NAME' => 'Внешний код',
                'IS_REQUIRED' => 'Y',
                'DEFAULT_VALUE' => '',
            ],
            'CODE' => [
                'NAME' => 'Символьный код',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => [
                    'UNIQUE' => 'N',
                    'TRANSLITERATION' => 'N',
                    'TRANS_LEN' => 100,
                    'TRANS_CASE' => 'L',
                    'TRANS_SPACE' => '-',
                    'TRANS_OTHER' => '-',
                    'TRANS_EAT' => 'Y',
                    'USE_GOOGLE' => 'N',
                ],
            ],
            'TAGS' => [
                'NAME' => 'Теги',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => '',
            ],
            'SECTION_NAME' => [
                'NAME' => 'Название',
                'IS_REQUIRED' => 'Y',
                'DEFAULT_VALUE' => '',
            ],
            'SECTION_PICTURE' => [
                'NAME' => 'Картинка для анонса',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => [
                    'FROM_DETAIL' => 'N',
                    'SCALE' => 'N',
                    'WIDTH' => '',
                    'HEIGHT' => '',
                    'IGNORE_ERRORS' => 'N',
                    'METHOD' => 'resample',
                    'COMPRESSION' => 95,
                    'DELETE_WITH_DETAIL' => 'N',
                    'UPDATE_WITH_DETAIL' => 'N',
                    'USE_WATERMARK_TEXT' => 'N',
                    'WATERMARK_TEXT' => '',
                    'WATERMARK_TEXT_FONT' => '',
                    'WATERMARK_TEXT_COLOR' => '',
                    'WATERMARK_TEXT_SIZE' => '',
                    'WATERMARK_TEXT_POSITION' => 'tl',
                    'USE_WATERMARK_FILE' => 'N',
                    'WATERMARK_FILE' => '',
                    'WATERMARK_FILE_ALPHA' => '',
                    'WATERMARK_FILE_POSITION' => 'tl',
                    'WATERMARK_FILE_ORDER' => null,
                ],
            ],
            'SECTION_DESCRIPTION_TYPE' => [
                'NAME' => 'Тип описания',
                'IS_REQUIRED' => 'Y',
                'DEFAULT_VALUE' => 'text',
            ],
            'SECTION_DESCRIPTION' => [
                'NAME' => 'Описание',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => '',
            ],
            'SECTION_DETAIL_PICTURE' => [
                'NAME' => 'Детальная картинка',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => [
                    'SCALE' => 'N',
                    'WIDTH' => '',
                    'HEIGHT' => '',
                    'IGNORE_ERRORS' => 'N',
                    'METHOD' => 'resample',
                    'COMPRESSION' => 95,
                    'USE_WATERMARK_TEXT' => 'N',
                    'WATERMARK_TEXT' => '',
                    'WATERMARK_TEXT_FONT' => '',
                    'WATERMARK_TEXT_COLOR' => '',
                    'WATERMARK_TEXT_SIZE' => '',
                    'WATERMARK_TEXT_POSITION' => 'tl',
                    'USE_WATERMARK_FILE' => 'N',
                    'WATERMARK_FILE' => '',
                    'WATERMARK_FILE_ALPHA' => '',
                    'WATERMARK_FILE_POSITION' => 'tl',
                    'WATERMARK_FILE_ORDER' => null,
                ],
            ],
            'SECTION_XML_ID' => [
                'NAME' => 'Внешний код',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => '',
            ],
            'SECTION_CODE' => [
                'NAME' => 'Символьный код',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => [
                    'UNIQUE' => 'N',
                    'TRANSLITERATION' => 'N',
                    'TRANS_LEN' => 100,
                    'TRANS_CASE' => 'L',
                    'TRANS_SPACE' => '-',
                    'TRANS_OTHER' => '-',
                    'TRANS_EAT' => 'Y',
                    'USE_GOOGLE' => 'N',
                ],
            ],
            'LOG_SECTION_ADD' => [
                'NAME' => 'LOG_SECTION_ADD',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => null,
            ],
            'LOG_SECTION_EDIT' => [
                'NAME' => 'LOG_SECTION_EDIT',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => null,
            ],
            'LOG_SECTION_DELETE' => [
                'NAME' => 'LOG_SECTION_DELETE',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => null,
            ],
            'LOG_ELEMENT_ADD' => [
                'NAME' => 'LOG_ELEMENT_ADD',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => null,
            ],
            'LOG_ELEMENT_EDIT' => [
                'NAME' => 'LOG_ELEMENT_EDIT',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => null,
            ],
            'LOG_ELEMENT_DELETE' => [
                'NAME' => 'LOG_ELEMENT_DELETE',
                'IS_REQUIRED' => 'N',
                'DEFAULT_VALUE' => null,
            ],
        ]);
        $helper->Iblock()->saveGroupPermissions($iblockId, [
            'administrators' => 'X',
        ]);
        $helper->Iblock()->saveProperty($iblockId, [
            'NAME' => 'Test number',
            'ACTIVE' => 'Y',
            'SORT' => '500',
            'CODE' => 'TEST_NUMBER',
            'DEFAULT_VALUE' => '',
            'PROPERTY_TYPE' => 'N',
            'ROW_COUNT' => '1',
            'COL_COUNT' => '30',
            'LIST_TYPE' => 'L',
            'MULTIPLE' => 'N',
            'XML_ID' => null,
            'FILE_TYPE' => '',
            'MULTIPLE_CNT' => '5',
            'LINK_IBLOCK_ID' => '0',
            'WITH_DESCRIPTION' => 'N',
            'SEARCHABLE' => 'N',
            'FILTRABLE' => 'N',
            'IS_REQUIRED' => 'N',
            'VERSION' => '1',
            'USER_TYPE' => null,
            'USER_TYPE_SETTINGS' => null,
            'HINT' => '',
        ]);
        $helper->Iblock()->saveProperty($iblockId, [
            'NAME' => 'Test string',
            'ACTIVE' => 'Y',
            'SORT' => '500',
            'CODE' => 'TEST_STRING',
            'DEFAULT_VALUE' => '',
            'PROPERTY_TYPE' => 'S',
            'ROW_COUNT' => '1',
            'COL_COUNT' => '30',
            'LIST_TYPE' => 'L',
            'MULTIPLE' => 'N',
            'XML_ID' => null,
            'FILE_TYPE' => '',
            'MULTIPLE_CNT' => '5',
            'LINK_IBLOCK_ID' => '0',
            'WITH_DESCRIPTION' => 'N',
            'SEARCHABLE' => 'N',
            'FILTRABLE' => 'N',
            'IS_REQUIRED' => 'N',
            'VERSION' => '1',
            'USER_TYPE' => null,
            'USER_TYPE_SETTINGS' => null,
            'HINT' => '',
        ]);
        $helper->Iblock()->saveProperty($iblockId, [
            'NAME' => 'Test file',
            'ACTIVE' => 'Y',
            'SORT' => '500',
            'CODE' => 'TEST_FILE',
            'DEFAULT_VALUE' => '',
            'PROPERTY_TYPE' => 'F',
            'ROW_COUNT' => '1',
            'COL_COUNT' => '30',
            'LIST_TYPE' => 'L',
            'MULTIPLE' => 'N',
            'XML_ID' => null,
            'FILE_TYPE' => '',
            'MULTIPLE_CNT' => '5',
            'LINK_IBLOCK_ID' => '0',
            'WITH_DESCRIPTION' => 'N',
            'SEARCHABLE' => 'N',
            'FILTRABLE' => 'N',
            'IS_REQUIRED' => 'N',
            'VERSION' => '1',
            'USER_TYPE' => null,
            'USER_TYPE_SETTINGS' => null,
            'HINT' => '',
        ]);
        $helper->Iblock()->saveProperty($iblockId, [
            'NAME' => 'Test list',
            'ACTIVE' => 'Y',
            'SORT' => '500',
            'CODE' => 'TEST_LIST',
            'DEFAULT_VALUE' => '',
            'PROPERTY_TYPE' => 'L',
            'ROW_COUNT' => '1',
            'COL_COUNT' => '30',
            'LIST_TYPE' => 'L',
            'MULTIPLE' => 'N',
            'XML_ID' => null,
            'FILE_TYPE' => '',
            'MULTIPLE_CNT' => '5',
            'LINK_IBLOCK_ID' => '0',
            'WITH_DESCRIPTION' => 'N',
            'SEARCHABLE' => 'N',
            'FILTRABLE' => 'N',
            'IS_REQUIRED' => 'N',
            'VERSION' => '1',
            'USER_TYPE' => null,
            'USER_TYPE_SETTINGS' => null,
            'HINT' => '',
            'VALUES' => [
                0 => [
                    'VALUE' => '20902',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'cccad7718c8e9d560093fe5abcf069ec',
                ],
                1 => [
                    'VALUE' => '20902',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '8cc8a941a0fbadbcc06adcd398f433b5',
                ],
                2 => [
                    'VALUE' => 'DICH',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'ecdc55245e27eb7edb13a50513b645ef',
                ],
                3 => [
                    'VALUE' => 'Test Olezhka',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '949f9991e2eb1cd18d5bd64ffec53186',
                ],
                4 => [
                    'VALUE' => 'Test Olezhka',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'efb461a61b625b2c9813c9ba975166a6',
                ],
                5 => [
                    'VALUE' => 'test-list 10',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'a9a91d11b621c0f138d59982fb230995',
                ],
                6 => [
                    'VALUE' => 'test-list 11',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'c3c161bd658b4a2411fe2c446acd28ee',
                ],
                7 => [
                    'VALUE' => 'test-list 12',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'd6254eae2ec31056db7518fd7ffba5a5',
                ],
                8 => [
                    'VALUE' => 'test-list 2',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '804b1b62e1a6d881f8261e0f27406ad9',
                ],
                9 => [
                    'VALUE' => 'test-list 3',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'c30787cccbc59b82789237f9ae743558',
                ],
                10 => [
                    'VALUE' => 'test-list 4',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '239bf75a107cce8c2a2a5dc91ff7a213',
                ],
                11 => [
                    'VALUE' => 'test-list 5',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '23f02796decec26bb47feb1b531732b5',
                ],
                12 => [
                    'VALUE' => 'test-list 6',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '0d6b4ec5a096e67f72fda65a5ff7ba5d',
                ],
                13 => [
                    'VALUE' => 'test-list 8',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'e26eabd80cc6da5766fe3d7d5f7aaa6d',
                ],
                14 => [
                    'VALUE' => 'test-list 9',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '431219939b3efbb9aaeeb3b10e89178c',
                ],
                15 => [
                    'VALUE' => 'test22812zxczxcxc',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '8f56f5b52f63615d10e963f32787dfcf',
                ],
                16 => [
                    'VALUE' => 'test22812zxczxcxc',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'ed3ae18cd219832f3f12d71f759dfaae',
                ],
                17 => [
                    'VALUE' => 'test22812zxczxcxc',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '26438b8a362fdc1be27b63b870ee17ff',
                ],
                18 => [
                    'VALUE' => 'test22812zxczxcxc',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '344a41af6356995e73eca949ad12d2f2',
                ],
                19 => [
                    'VALUE' => 'test22812zxczxcxc',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'e56f8b0cfcc74390a572cef638748d8b',
                ],
                20 => [
                    'VALUE' => 'test22812zxczxcxc',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '0c8af455df0eca64c0f867a2bfa7c6f5',
                ],
                21 => [
                    'VALUE' => 'zxc',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '67260becedf10c6b289f7c5260675064',
                ],
                22 => [
                    'VALUE' => 'zxc',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '98b157f932d7adc48b1c32d66c528450',
                ],
                23 => [
                    'VALUE' => 'Виталя',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'c135ee67a1f67e6f3ff9143769b38a1e',
                ],
                24 => [
                    'VALUE' => 'Виталя',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '4805b7f557bb12d28964ae306cbdf989',
                ],
                25 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '4596acaa42016179b5ae3261e34076a7',
                ],
                26 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '2c7ea3794d977ab6f33ea8deefa516ee',
                ],
                27 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '539391b431b2b2ce3d6d825eb4b5f024',
                ],
                28 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'd5a4535a10be8efc1c2b473b8987c34a',
                ],
                29 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'add2de3f167c36fbcb48043f180ce5bf',
                ],
                30 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '90fbd323529287101c1b9599f7e8d9d3',
                ],
                31 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '4aab0eb0372da2cb4f2c26aa57611535',
                ],
                32 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'de3a793a7dacca839f44cf11ac17683e',
                ],
                33 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'b10b3567d0e6bdaab04a581f195b36b7',
                ],
                34 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '7b883a0ee05d14d85e172ea0ad5fe0a6',
                ],
                35 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '4791f8a0c22cc74484e32240575bb4eb',
                ],
                36 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '3cb207a7b7b12ecd513f666223476f6a',
                ],
                37 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => '935863beec56f59c22b1c7e3d2c97b1a',
                ],
                38 => [
                    'VALUE' => 'олег',
                    'DEF' => 'N',
                    'SORT' => '500',
                    'XML_ID' => 'a483428d62b8f19e1f217a4df875cab2',
                ],
            ],
            'FEATURES' => [
                0 => [
                    'MODULE_ID' => 'iblock',
                    'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
                    'IS_ENABLED' => 'N',
                ],
                1 => [
                    'MODULE_ID' => 'iblock',
                    'FEATURE_ID' => 'LIST_PAGE_SHOW',
                    'IS_ENABLED' => 'N',
                ],
            ],
        ]);
        $helper->Iblock()->saveProperty($iblockId, [
            'NAME' => 'Test iblock element bind',
            'ACTIVE' => 'Y',
            'SORT' => '500',
            'CODE' => 'TEST_IB_ELEMENT_BIND',
            'DEFAULT_VALUE' => '',
            'PROPERTY_TYPE' => 'E',
            'ROW_COUNT' => '1',
            'COL_COUNT' => '30',
            'LIST_TYPE' => 'L',
            'MULTIPLE' => 'N',
            'XML_ID' => null,
            'FILE_TYPE' => '',
            'MULTIPLE_CNT' => '5',
            'LINK_IBLOCK_ID' => 'test:Test1',
            'WITH_DESCRIPTION' => 'N',
            'SEARCHABLE' => 'N',
            'FILTRABLE' => 'N',
            'IS_REQUIRED' => 'N',
            'VERSION' => '1',
            'USER_TYPE' => null,
            'USER_TYPE_SETTINGS' => null,
            'HINT' => '',
            'FEATURES' => [
                0 => [
                    'MODULE_ID' => 'iblock',
                    'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
                    'IS_ENABLED' => 'N',
                ],
                1 => [
                    'MODULE_ID' => 'iblock',
                    'FEATURE_ID' => 'LIST_PAGE_SHOW',
                    'IS_ENABLED' => 'N',
                ],
            ],
        ]);
        $helper->Iblock()->saveProperty($iblockId, [
            'NAME' => 'Test higloadblock element bind ',
            'ACTIVE' => 'Y',
            'SORT' => '500',
            'CODE' => 'TEST_HB_ELEMENT_BIND',
            'DEFAULT_VALUE' => '',
            'PROPERTY_TYPE' => 'S',
            'ROW_COUNT' => '1',
            'COL_COUNT' => '30',
            'LIST_TYPE' => 'L',
            'MULTIPLE' => 'N',
            'XML_ID' => null,
            'FILE_TYPE' => '',
            'MULTIPLE_CNT' => '5',
            'LINK_IBLOCK_ID' => '0',
            'WITH_DESCRIPTION' => 'N',
            'SEARCHABLE' => 'N',
            'FILTRABLE' => 'N',
            'IS_REQUIRED' => 'N',
            'VERSION' => '1',
            'USER_TYPE' => 'directory',
            'USER_TYPE_SETTINGS' => [
                'size' => 1,
                'width' => 0,
                'group' => 'N',
                'multiple' => 'N',
                'TABLE_NAME' => 'test_high_load_block',
            ],
            'HINT' => '',
            'FEATURES' => [
                0 => [
                    'MODULE_ID' => 'iblock',
                    'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
                    'IS_ENABLED' => 'N',
                ],
                1 => [
                    'MODULE_ID' => 'iblock',
                    'FEATURE_ID' => 'LIST_PAGE_SHOW',
                    'IS_ENABLED' => 'N',
                ],
            ],
        ]);
        $helper->Iblock()->saveProperty($iblockId, [
            'NAME' => 'Test user bind',
            'ACTIVE' => 'Y',
            'SORT' => '500',
            'CODE' => 'TEST_USER_BIND',
            'DEFAULT_VALUE' => '',
            'PROPERTY_TYPE' => 'S',
            'ROW_COUNT' => '1',
            'COL_COUNT' => '30',
            'LIST_TYPE' => 'L',
            'MULTIPLE' => 'N',
            'XML_ID' => null,
            'FILE_TYPE' => '',
            'MULTIPLE_CNT' => '5',
            'LINK_IBLOCK_ID' => '0',
            'WITH_DESCRIPTION' => 'N',
            'SEARCHABLE' => 'N',
            'FILTRABLE' => 'N',
            'IS_REQUIRED' => 'N',
            'VERSION' => '1',
            'USER_TYPE' => 'UserID',
            'USER_TYPE_SETTINGS' => null,
            'HINT' => '',
        ]);
        $helper->Iblock()->saveProperty($iblockId, [
            'NAME' => 'Test iblock section bind',
            'ACTIVE' => 'Y',
            'SORT' => '500',
            'CODE' => 'TEST_IB_SECTION_BIND',
            'DEFAULT_VALUE' => '',
            'PROPERTY_TYPE' => 'G',
            'ROW_COUNT' => '1',
            'COL_COUNT' => '30',
            'LIST_TYPE' => 'L',
            'MULTIPLE' => 'N',
            'XML_ID' => null,
            'FILE_TYPE' => '',
            'MULTIPLE_CNT' => '5',
            'LINK_IBLOCK_ID' => 'test:Test1',
            'WITH_DESCRIPTION' => 'N',
            'SEARCHABLE' => 'N',
            'FILTRABLE' => 'N',
            'IS_REQUIRED' => 'N',
            'VERSION' => '1',
            'USER_TYPE' => null,
            'USER_TYPE_SETTINGS' => null,
            'HINT' => '',
            'FEATURES' => [
                0 => [
                    'MODULE_ID' => 'iblock',
                    'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
                    'IS_ENABLED' => 'N',
                ],
                1 => [
                    'MODULE_ID' => 'iblock',
                    'FEATURE_ID' => 'LIST_PAGE_SHOW',
                    'IS_ENABLED' => 'N',
                ],
            ],
        ]);
        $helper->Iblock()->saveProperty($iblockId, [
            'NAME' => 'Test file multiple',
            'ACTIVE' => 'Y',
            'SORT' => '500',
            'CODE' => 'TEST_FILE_MULTIPLE',
            'DEFAULT_VALUE' => '',
            'PROPERTY_TYPE' => 'F',
            'ROW_COUNT' => '1',
            'COL_COUNT' => '30',
            'LIST_TYPE' => 'L',
            'MULTIPLE' => 'Y',
            'XML_ID' => null,
            'FILE_TYPE' => '',
            'MULTIPLE_CNT' => '5',
            'LINK_IBLOCK_ID' => '0',
            'WITH_DESCRIPTION' => 'N',
            'SEARCHABLE' => 'N',
            'FILTRABLE' => 'N',
            'IS_REQUIRED' => 'N',
            'VERSION' => '1',
            'USER_TYPE' => null,
            'USER_TYPE_SETTINGS' => null,
            'HINT' => '',
        ]);
        $helper->UserOptions()->saveElementGrid($iblockId, [
            'views' => [
                'default' => [
                    'columns' => [
                        0 => '',
                    ],
                    'columns_sizes' => [
                        'expand' => 1,
                        'columns' => [
                        ],
                    ],
                    'sticked_columns' => [
                    ],
                    'custom_names' => [
                    ],
                ],
            ],
            'filters' => [
            ],
            'current_view' => 'default',
        ]);
        $helper->UserOptions()->saveSectionGrid($iblockId, [
            'views' => [
                'default' => [
                    'columns' => [
                        0 => '',
                    ],
                    'columns_sizes' => [
                        'expand' => 1,
                        'columns' => [
                        ],
                    ],
                    'sticked_columns' => [
                    ],
                    'custom_names' => [
                    ],
                ],
            ],
            'filters' => [
            ],
            'current_view' => 'default',
        ]);
    }

    public function down()
    {
        //your code ...
    }
}
